displayName: Login Auth
type: middleware
iconPath: .assets/icon.png

import: github.com/dusty-cjh/loginAuth

summary: '[Demo] Add Request Header'

testData:
  Headers:
    X-Demo: test
    X-URL: '{{URL}}'
